development:
  adapter: postgresql
  encoding: unicode
  database: mozaiku_dev
  host: localhost
  pool: 5
  username: frading2
  password: password


production:
  adapter: postgresql
  encoding: unicode
  database: guillaumefradin_dev
  pool: 5
  username: frading
  password: password
